# Generated by Django 4.2.2 on 2023-06-21 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("aici", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="voc",
            name="author",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="voc",
            name="comment",
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="voc",
            name="phone",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="voc",
            name="tt",
            field=models.CharField(max_length=30),
        ),
    ]
