# Generated by Django 4.2.2 on 2023-06-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aici", "0002_voc_author_alter_voc_comment_alter_voc_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voc",
            name="voc_status",
            field=models.TextField(null=True),
        ),
    ]
