# Generated by Django 4.2.2 on 2023-06-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aici", "0005_alter_voc_repair_status_alter_voc_voc_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voc",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
