# Generated by Django 4.2.2 on 2023-07-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aici", "0006_alter_voc_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voc",
            name="comment",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
