# Generated by Django 4.2.2 on 2023-06-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Gongsa", "0008_rename_additional_field_profile_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="department",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
