# Generated by Django 4.2.2 on 2023-06-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Gongsa", "0010_post_agency_post_phone_profile_agency_profile_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="agency",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
