# Generated by Django 4.2.2 on 2023-07-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Gongsa", "0011_alter_post_agency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
